print("Hello Kallen") 
#print("lolo")
n = input ("what your name?")
print("kallen", n )
s = input ("Do you have boyfriend ?")
print("Yes, of course", s)
p = input ("Your birth ?")
age = 2018 - int(p)
print(age)
